# Netlify configuration file

[build]
  # This directory contains the public assets and the serverless function.
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  # Redirect requests from /api/* to our serverless function
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 # OK
